### PR TITLE
Move employees config to sinatra yaml config

### PR DESCRIPTION
**Pull request by highb**
This commit uses Sinatra's `config_file` lib to load up a config
file, either at 'config.yml`in pwd or at ENV['CONFIG_FILE'], which
is then used to populate the`employees` array, which is used to
determine "waiting on us" vs "waiting on contributor"

### CODE REVIEW

**Comment by whopper** [comment]
Ooh I didn't even notice this PR! I'll get this in ASAP - will require a rebase but I can take care of it.

**Comment by highb** [comment]
@whopper Added `phongdly` to the employees config and rebased (the employee list was the only conflict)

**Comment by highb** [comment]
@whopper Anything you want me to fixup on this?

**Comment by whopper** [comment]
@highb nope, this looks amazing! I'll need to figure out how to use it in heroku but 👍

**Pull request merged**
